
services:
  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: developer
      POSTGRES_DB: my_postgres
    ports:
      - "5432:5432"
    volumes:
      - C:/Users/dalca/Desktop/data:/var/lib/postgresql/data